-- Project database foundation for NH Property Intelligence.
-- Run as ACCOUNTADMIN after 01_roles.sql.

USE ROLE ACCOUNTADMIN;

CREATE DATABASE IF NOT EXISTS NH_PROPERTY_INTELLIGENCE;

GRANT USAGE ON DATABASE NH_PROPERTY_INTELLIGENCE TO ROLE NHPI_ENGINEER;
GRANT CREATE SCHEMA ON DATABASE NH_PROPERTY_INTELLIGENCE TO ROLE NHPI_ENGINEER;
