-- Verify that the NH Property Intelligence Snowflake foundation is ready for live execution.
-- Run as NHPI_ENGINEER after scripts 01-06 have completed successfully.

USE ROLE NHPI_ENGINEER;
USE WAREHOUSE NHPI_XS;
USE DATABASE NH_PROPERTY_INTELLIGENCE;
USE SCHEMA RAW;

SELECT CURRENT_ACCOUNT() AS account_identifier,
       CURRENT_USER() AS user_name,
       CURRENT_ROLE() AS active_role,
       CURRENT_WAREHOUSE() AS active_warehouse,
       CURRENT_DATABASE() AS active_database,
       CURRENT_SCHEMA() AS active_schema;

SHOW SCHEMAS IN DATABASE NH_PROPERTY_INTELLIGENCE;
SHOW TABLES IN SCHEMA NH_PROPERTY_INTELLIGENCE.RAW;

SELECT 'CENSUS_ACS_MUNICIPALITY' AS table_name, COUNT(*) AS row_count
FROM NH_PROPERTY_INTELLIGENCE.RAW.CENSUS_ACS_MUNICIPALITY
UNION ALL
SELECT 'DRA_MUNICIPAL_TAX_RATES', COUNT(*)
FROM NH_PROPERTY_INTELLIGENCE.RAW.DRA_MUNICIPAL_TAX_RATES
UNION ALL
SELECT 'FHFA_COUNTY_HPI', COUNT(*)
FROM NH_PROPERTY_INTELLIGENCE.RAW.FHFA_COUNTY_HPI;
