select
    county_subdivision_geoid as municipality_geoid,
    acs_vintage,
    total_population,
    median_household_income,
    median_owner_occupied_home_value,
    median_gross_rent,
    total_housing_units,
    occupied_housing_units,
    owner_occupied_housing_units,
    home_value_to_income_ratio,
    annual_rent_to_income_ratio,
    owner_occupancy_rate,
    vacancy_proxy_rate,
    total_population_moe,
    median_household_income_moe,
    median_owner_occupied_home_value_moe,
    median_gross_rent_moe,
    total_housing_units_moe,
    occupied_housing_units_moe,
    owner_occupied_housing_units_moe,
    source_system,
    source_endpoint,
    source_requested_at,
    ingested_at,
    ingestion_run_id,
    row_hash
from {{ ref('int_acs_housing_metrics') }}
